//! Bulk-load helpers shared by the archive re-encode and the archive -> state
//! migration: both build SST files from an ascending key stream and hand them
//! to `ingest_external_file`, which skips the WAL, the memtable and the
//! compactions a batch write would pay for.

use rocksdb::{IngestExternalFileOptions, Options, SstFileWriter};

use crate::db_impl::error::Error;

/// SstFileWriter Options used for archive bulk-load. Compression matches the
/// L0/L1 setting of the large CFs (LZ4) so RocksDB does not transcode the
/// ingested file when cascading. The default BytewiseComparator matches the
/// CF comparator. Block-table layout is left default; bloom/index are
/// regenerated by the final manual `compact()` when files cascade out of L0.
pub(crate) fn sst_writer_options() -> Options {
    let mut opts = Options::default();
    opts.set_compression_type(rocksdb::DBCompressionType::Lz4);
    opts
}

/// Default IngestExternalFileOptions for archive bulk-load. `move_files=true`
/// renames the file into RocksDB's data directory instead of copying — the
/// caller is responsible for ensuring the source path is on the same
/// filesystem as the database. Other options are left at RocksDB defaults
/// (`snapshot_consistency=true`, `allow_global_seqno=true`,
/// `allow_blocking_flush=true`, `ingest_behind=false`); these are correct
/// for the bulk-load workload, where we do not write to the target CFs'
/// memtables and depend on global seqno assignment for correct read-merge
/// of any duplicate keys produced by crash-resume re-ingest.
pub(crate) fn ingest_external_file_options() -> IngestExternalFileOptions {
    let mut opts = IngestExternalFileOptions::default();
    opts.set_move_files(true);
    opts
}

/// Streams **strictly-ascending** `(key, value)` pairs into a series of rolled
/// SST files for later `ingest_external_file`. Keys must be globally ascending
/// across all `put` calls; the file is rolled whenever it exceeds `roll_bytes`
/// (any split of an ascending stream yields non-overlapping files, which ingest
/// can place across levels instead of piling into L0).
pub(crate) struct SstSink<'a> {
    opts: &'a Options,
    tmp_dir: std::path::PathBuf,
    name: String,
    roll_bytes: u64,
    seq: u64,
    writer: Option<SstFileWriter<'a>>,
    cur_path: std::path::PathBuf,
    has_rows: bool,
    paths: Vec<std::path::PathBuf>,
}

impl<'a> SstSink<'a> {
    pub(crate) fn new(
        opts: &'a Options,
        tmp_dir: std::path::PathBuf,
        name: String,
        roll_bytes: u64,
    ) -> Self {
        Self {
            opts,
            tmp_dir,
            name,
            roll_bytes,
            seq: 0,
            writer: None,
            cur_path: std::path::PathBuf::new(),
            has_rows: false,
            paths: Vec::new(),
        }
    }

    pub(crate) fn put(&mut self, key: &[u8], value: &[u8]) -> Result<(), Error> {
        if self.writer.is_none() {
            let p = self
                .tmp_dir
                .join(format!("{}_{:06}.sst", self.name, self.seq));
            self.seq += 1;
            let w = SstFileWriter::create(self.opts);
            w.open(&p)?;
            self.writer = Some(w);
            self.cur_path = p;
            self.has_rows = false;
        }
        let w = self.writer.as_mut().unwrap();
        w.put(key, value)?;
        self.has_rows = true;
        if w.file_size() >= self.roll_bytes {
            self.writer.take().unwrap().finish()?;
            self.paths.push(std::mem::take(&mut self.cur_path));
        }
        Ok(())
    }

    pub(crate) fn finish(mut self) -> Result<Vec<std::path::PathBuf>, Error> {
        if let Some(mut w) = self.writer.take() {
            if self.has_rows {
                w.finish()?;
                self.paths.push(self.cur_path);
            }
        }
        Ok(self.paths)
    }
}
