available_nodes_ttl: 5
chain_id: 4217
version: f490914c
check_interval_ms: 20
check_num: 3
consistency_db_path: /tempo/consistency_db
etcd_endpoints:
- 127.0.0.1:2379
inner_brokers:
- b-1.chaintablenodexpi.udy5cj.c4.kafka.ap-northeast-1.amazonaws.com:9092
inner_new_block_group_id: consistency-group-4217-f490914c
inner_new_block_topic: nodex_pipeline_4217_f490914c
listen: 0.0.0.0:8886
outer_brokers:
- b-1.chaintablenodexpi.udy5cj.c4.kafka.ap-northeast-1.amazonaws.com:9092
outer_new_block_topic: pipeline_4217
outer_version_new_block_topic: pipeline_4217_f490914c
outer_s3_bucket: chaintable-pipeline--apne1-az4--x-s3
outer_s3_region: ap-northeast-1
ready_ratio: 0.8
